# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 


[window]

[colors]

[colors.primary]
background = "#2c2d37"
foreground = "#ceb8b0"

[colors.normal]
black   = "#2c2d37"
red     = "#c13e46"
green   = "#adc4b3"
yellow  = "#b89030"
blue    = "#9287b0"
magenta = "#ad93b7"
cyan    = "#238e9e"
white   = "#ceb8b0"

[colors.bright]
black   = "#55595d"
red     = "#d8979a"
green   = "#a8bfb8"
yellow  = "#d2833b"
blue    = "#4e6aa0"
magenta = "#b1a9c2"
cyan    = "#8eb3c0"
white   = "#dfc0b0"

[colors.cursor]
text   = "#2c2d37"
cursor = "#dfc0b0"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
