# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[main]
font=monospace:size=11
pad=14x14 center

[colors-dark]
foreground=ceb8b0
background=2c2d37
# alpha=0.95
cursor=2c2d37 dfc0b0

regular0=2c2d37
regular1=c13e46
regular2=adc4b3
regular3=b89030
regular4=9287b0
regular5=ad93b7
regular6=238e9e
regular7=ceb8b0

bright0=55595d
bright1=d8979a
bright2=a8bfb8
bright3=d2833b
bright4=4e6aa0
bright5=b1a9c2
bright6=8eb3c0
bright7=dfc0b0

selection-foreground=2c2d37
selection-background=2488cb
